apiVersion: v1
kind: ConfigMap

metadata:
  name: url-shortener-config
  namespace: url-shortener

data:
  NODE_ENV: "production"

  PORT: "3000"

  BASE_URL: "http://localhost:3000"

  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/url_shortener"

  REDIS_URL: "redis://redis:6379"

  REDIS_CACHE_ENABLED: "true"

  BENCHMARK_MODE: "false"

  LOG_LEVEL: "info"

  JWT_EXPIRES_IN: "7d"