apiVersion: v1
kind: Secret

metadata:
  name: url-shortener-secret
  namespace: url-shortener

type: Opaque

stringData:
  GOOGLE_CLIENT_ID: "91790939490-ed0fnav0oh2jl2n8df2eogn7mdb3gisn.apps.googleusercontent.com"

  JWT_SECRET: "your-super-long-random-secret-key-at-least-32-characters"